# Generated by Django 2.2.3 on 2019-07-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=20)),
                ('api_data', models.CharField(max_length=256)),
                ('api_report', models.CharField(max_length=256)),
                ('process_data', models.CharField(max_length=256)),
                ('process_report', models.CharField(max_length=256)),
                ('smtp_host', models.CharField(max_length=50)),
                ('from_addr', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('to_addr', models.CharField(max_length=256)),
            ],
        ),
    ]
