# Generated by Django 2.2.3 on 2019-07-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0002_confs'),
    ]

    operations = [
        migrations.AddField(
            model_name='confs',
            name='username',
            field=models.CharField(default='admin', max_length=20, unique=True),
        ),
    ]
