# Generated by Django 2.2.3 on 2019-07-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0003_confs_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ticket',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
