# Generated by Django 2.2.3 on 2019-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0004_userinfo_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
